cocktail-bar/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'categories#index'

  get 'search', to: 'cocktails#search'
  post 'create', to: 'cocktails#create'
  get 'cocktail_form', to: 'cocktails#cocktail_form'
  put 'set_like', to: 'cocktails#set_like'
  put 'set_like_show', to: 'cocktails#set_like_show'
  put 'set_rate_one', to: 'cocktails#set_rate_one'
  put 'set_rate_two', to: 'cocktails#set_rate_two'
  put 'set_rate_three', to: 'cocktails#set_rate_three'
  put 'set_rate_four', to: 'cocktails#set_rate_four'
  put 'set_rate_five', to: 'cocktails#set_rate_five'
  get 'cocktail_favorites', to: 'cocktails#favorites'

  resources :categories do
    resources :cocktails do
      get 'add_ingredient_form', to: 'cocktails#add_ingredient_form'
      post 'add_ingredient', to: 'cocktails#add_ingredient'
      resources :ingredients
    end
  end
end

cocktail-bar/app/models/cocktail.rb
# frozen_string_literal: true

class Cocktail < ApplicationRecord
  belongs_to :category
  has_and_belongs_to_many :ingredients, through: Ingredient

  validates :name, presence: true
  validates :picture, presence: true
  validates :instructions, presence: true
  validates :like, presence: true
  validates :rating, presence: true
end

cocktail-bar/app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :set_category, only: %i[show destroy set_like set_rate set_like_show set_rate_one set_rate_two set_rate_three set_rate_four set_rate_five]
  before_action :set_cocktail, only: %i[show destroy set_like set_rate set_like_show set_rate_one set_rate_two set_rate_three set_rate_four set_rate_five]
  before_action :create_category, only: [:create]

  def search
    if params[:search]
      @search_result = Cocktail.all.filter do |cocktail|
        cocktail.name.downcase.include?(params[:search].to_s.downcase) || cocktail.ingredients.any? do |ingredient|
          ingredient.name.downcase.include?(params[:search].to_s.downcase)
        end
      end
      @search_result.sort! { |a, b| a.name <=> b.name }
    else
      @search_result = Cocktail.all
    end
  end

  def show
    @ingredients = @cocktail.ingredients
  end

  def new
    # @cocktail = @category.cocktails.build
  end

  def create
    @cocktail = @category.cocktails.build(name: params[:name], instructions: params[:instructions],
                                          picture: params[:picture], like: 0, rating: 0)

    @cocktail.save
    redirect_to category_cocktail_path(category_id: @category.id, id: @cocktail.id), notice: 'Cocktail added successfully.'

  end

  def edit; end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to categories_path, notice: 'Cocktails updated successfully.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @cocktail.destroy

    redirect_to categories_path, notice: 'Cocktail deleted successfully.'
  end

  def add_ingredient_form
    @category = Category.find(params[:category_id])
    @cocktail = @category.cocktails.find(params[:cocktail_id])
  end

  def add_ingredient
    @cocktail = Cocktail.find(params[:id])
    new_ingredient = Ingredient.find(params[:ingredient])
    if @cocktail.ingredients.any? { |ingredient| ingredient == new_ingredient }
      redirect_to :back, notice: 'Ingredient already present in this cocktail.'

    else
      @cocktail.ingredients << new_ingredient
      @cocktail.save
      redirect_to :back, notice: 'Ingredient added to cocktail successfully.'
    end
  end

  def favorites
    @favorites = Cocktail.all.find_all { |cocktail| cocktail.like == 1 }
  end

  def set_like
    @cocktail.like = if @cocktail.like == 1
                       0
                     else
                       1
                     end
    @cocktail.save
    render @category.cocktails
  end

  def set_like_show
    @cocktail.like = if @cocktail.like == 1
                       0
                     else
                       1
                     end
    @cocktail.save
    redirect_to categories_path
  end

  def check_like
    @cocktail.like
  end

  helper_method :check_like

  def set_rate_one
    if @cocktail.rating == 1
      @cocktail.rating = 0
    else
      @cocktail.rating = 1
    end
    @cocktail.save
    render @category.cocktails
  end

  def set_rate_two
    if @cocktail.rating == 2
      @cocktail.rating = 0
    else
      @cocktail.rating = 2
    end
    @cocktail.save
    render @category.cocktails
  end

  def set_rate_three
    if @cocktail.rating == 3
      @cocktail.rating = 0
    else
      @cocktail.rating = 3
    end
    @cocktail.save
    render @category.cocktails
  end

  def set_rate_four
    if @cocktail.rating == 4
      @cocktail.rating = 0
    else
      @cocktail.rating = 4
    end
    @cocktail.save
    render @category.cocktails
  end

  def set_rate_five
    if @cocktail.rating == 5
      @cocktail.rating = 0
    else
      @cocktail.rating = 5
    end
    @cocktail.save
    render @category.cocktails
  end

  private

  def create_category
    unless params[:picture].include?('https://')
      redirect_to :back, notice: "Picture urls must start with 'https://'"
    end
    if params[:new_category]
      if Category.all.any? { |category| category.name == params[:category_name] }
        redirect_to :back, notice: 'There already exists a category with that name.'
      elsif Cocktail.all.any? { |cocktail| cocktail.name == params[:name] }
        redirect_to :back, notice: 'There already exists a cocktail with that name.'
      elsif !helpers.image_valid?(params[:picture])
        redirect_to :back, notice: 'The provided image url is not valid.'
      else
        @category = Category.create(name: params[:category_name])
        @category.save
      end
    else
      @category = Category.find(params[:new_cocktail_category])
    end
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :picture, :instructions, :search_by_name)
  end

  def set_cocktail
    @cocktail = @category.cocktails.find(params[:id])
  end

  def set_category
    @category = Category.find(params[:category_id])
  end
end

cocktail-bar/app/helpers/cocktails_helper.rb
# frozen_string_literal: true

module CocktailsHelper
end

cocktail-bar/app/views/cocktails/_cocktail.html.erb
<%= turbo_frame_tag cocktail do %>
  <div class="cocktail">

    <%= link_to cocktail.name.titleize, category_cocktail_path(id: cocktail, category_id: cocktail.category_id), data: { turbo_frame: "cocktails" } %>

    <div class="_cocktail_header">
      <div>
      <%= image_tag(cocktail.picture, alt: cocktail.name, height: 150, width: 150) %>
        <div class="heart_btn" id="heart_btn_id">
          <%= form_tag(set_like_path(id: cocktail, category_id: cocktail.category_id), method: :put) do %>
            <%= if cocktail.like == 0
                  image_submit_tag('heart_empty.svg', alt: "Like", height: 24, width: 24)
                else
                  image_submit_tag('heart_full.svg', alt: "Like", height: 24, width: 24)
                end %>
          <% end %>
        </div>
        <div class="star_btn" id="star_btn_id" data-visibility-target="button" style="display: flex; align-items: center; justify-content: center">

          <%= form_tag(set_rate_one_path(id: cocktail, category_id: cocktail.category_id), method: :put) do %>
            <% if cocktail.rating < 1 %>
              <a style="display: inline-block"><%= image_submit_tag('star_empty.svg', alt: "Review 1/5", height: 24, width: 24) %></a>
            <% else %>
              <a style="display: inline-block"><%= image_submit_tag('star_full.svg', alt: "Review 1/5", height: 24, width: 24) %></a>
            <% end %>
          <% end %>

          <%= form_tag(set_rate_two_path(id: cocktail, category_id: cocktail.category_id), method: :put) do %>
            <% if cocktail.rating < 2 %>
              <a style="display: inline-block"><%= image_submit_tag('star_empty.svg', alt: "Review 2/5", height: 24, width: 24) %></a>
            <% else %>
              <a style="display: inline-block"><%= image_submit_tag('star_full.svg', alt: "Review 2/5", height: 24, width: 24) %></a>
            <% end %>
          <% end %>

          <%= form_tag(set_rate_three_path(id: cocktail, category_id: cocktail.category_id), method: :put) do %>
            <% if cocktail.rating < 3 %>
              <a style="display: inline-block"><%= image_submit_tag('star_empty.svg', alt: "Review 3/5", height: 24, width: 24) %></a>
            <% else %>
              <a style="display: inline-block"><%= image_submit_tag('star_full.svg', alt: "Review 3/5", height: 24, width: 24) %></a>
            <% end %>
          <% end %>

          <%= form_tag(set_rate_four_path(id: cocktail, category_id: cocktail.category_id), method: :put) do %>
            <% if cocktail.rating < 4 %>
              <a style="display: inline-block"><%= image_submit_tag('star_empty.svg', alt: "Review 4/5", height: 24, width: 24) %></a>
            <% else %>
              <a style="display: inline-block"><%= image_submit_tag('star_full.svg', alt: "Review 4/5", height: 24, width: 24) %></a>
            <% end %>
          <% end %>

          <%= form_tag(set_rate_five_path(id: cocktail, category_id: cocktail.category_id), method: :put) do %>
            <% if cocktail.rating < 5 %>
              <a style="display: inline-block"><%= image_submit_tag('star_empty.svg', alt: "Review 5/5", height: 24, width: 24) %></a>
            <% else %>
              <a style="display: inline-block"><%= image_submit_tag('star_full.svg', alt: "Review 5/5", height: 24, width: 24) %></a>
            <% end %>
          <% end %>
        </div>
      </div>
      <%= button_to image_tag('delete.png', width: 30, height: 30), category_cocktail_path(id: cocktail, category_id: cocktail.category_id), method: :delete, class: 'delete_btn' %>


    </div>
  </div>
<% end %>

cocktail-bar/app/views/cocktails/add_ingredient_form.html.erb
<%= turbo_frame_tag 'ingredient_form' do %>
  <%= form_tag(category_cocktail_add_ingredient_path(id: @cocktail.id), method: :post, class: 'form') do %>
    Ingredient: <%= select_tag "ingredient", options_from_collection_for_select(Ingredient.all.sort { |a,b| a.name <=> b.name }, "id", "name"), class: 'category_select' %><br>
    <%= submit_tag 'Submit', class: 'btn submit_cocktail' %>
  <% end %>
<% end %>

cocktail-bar/app/views/cocktails/cocktail_form.html.erb
<%= turbo_frame_tag 'cocktails' do %>

  <div class="cocktail_main">
    <h1 class="header">Add cocktail</h1>
    <%= form_tag(create_path, method: :post, class: 'form') do %>
      <%= label_tag(:new_category, "New category?", class: 'checkbox_label') %>
      <%= check_box_tag(:new_category, 1, false, id: "checkbox", class: 'checkbox') %>

      <div id="category-list">
        Category: <%= select_tag :new_cocktail_category, options_from_collection_for_select(Category.all, "id", "name"), class: 'category_select' %><br>
      </div>
      <div id="new-category-name" style="display: none">
        <%= text_field_tag(:category_name, params[:category_name], placeholder: "New category name...", class: 'cocktail_form_txt') %>
      </div>
      <%= text_field_tag(:name, params[:name], placeholder: "Cocktail name...", class: 'cocktail_form_txt') %><br>
      <%= text_field_tag(:picture, params[:picture], placeholder: "Cocktail picture url...", class: 'cocktail_form_txt') %><br>
      <%= text_area_tag(:instructions, params[:instructions], placeholder: "How to make cocktail instructions...", class: 'cocktail_form_txt') %>
      <br>
      <%= submit_tag "Submit", class: 'btn submit_cocktail' %>
    <% end %>
  </div>

  <script type="text/javascript">
      const checkbox = document.getElementById('checkbox');
      const details_div = document.getElementById('category-list');
      const new_category = document.getElementById('new-category-name');
      checkbox.onchange = function () {
          if (this.checked) {
              new_category.style.display = 'block';
              details_div.style.display = 'none';
          } else {
              details_div.style.display = 'block';
              new_category.style.display = 'none';
          }
      };
  </script>

<% end %>

cocktail-bar/app/views/cocktails/create.html.erb
<h1>CREATED COCKTAIL AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1>

cocktail-bar/app/views/cocktails/favorites.html.erb
<%= turbo_frame_tag 'cocktails' do %>
  <h1> <%= params[:search].to_s != '' ? "Search results for: " + params[:search] : "All Cocktails" %></h1><br>
  <%= render @favorites %>
<% end %>

cocktail-bar/app/views/cocktails/new.html.erb
<h1>CREATED COCKTAIL AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1>

cocktail-bar/app/views/cocktails/search.html.erb
<%= turbo_frame_tag 'cocktails' do %>
  <h1> <%= params[:search].to_s != '' ? "Search results for: " + params[:search] : "All Cocktails" %></h1><br>
  <%= render @search_result %>
<% end %>

cocktail-bar/app/views/cocktails/show.html.erb
<%= turbo_frame_tag "cocktails" do %>
  
  <%= turbo_stream_from "ingredients" %>
  <%= link_to sanitize("&larr; Go to #{@category.name}"), category_path(@category), class: "btn"%>
  <div class="cocktail_main">
    <h1 style="margin-bottom: 40px"><%= @cocktail.name.titleize %></h1>
    <%= image_tag(@cocktail.picture, alt: @cocktail.name, height: 300, width: 300) %>

    <h2 style="margin: 20px 0">Ingredients</h2>
    <div id="ingredients">
      <%= render @cocktail.ingredients.sort { |a, b| a.name <=> b.name } %>
    </div>
    <br>
    <%= link_to 'Add ingredient', category_cocktail_add_ingredient_form_path(category_id: @category, cocktail_id: @cocktail), class: 'submit_cocktail btn', data: { turbo_frame: 'ingredient_form' } %>
    <%= turbo_frame_tag 'ingredient_form' %>

    <h3>Instructions</h3>
    <%= @cocktail.instructions %>
  </div>
<% end %>