cocktail-bar/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'categories#index'

  get 'search', to: 'cocktails#search'
  post 'create', to: 'cocktails#create'
  get 'cocktail_form', to: 'cocktails#cocktail_form'
  put 'set_like', to: 'cocktails#set_like'
  put 'set_like_show', to: 'cocktails#set_like_show'
  put 'set_rate_one', to: 'cocktails#set_rate_one'
  put 'set_rate_two', to: 'cocktails#set_rate_two'
  put 'set_rate_three', to: 'cocktails#set_rate_three'
  put 'set_rate_four', to: 'cocktails#set_rate_four'
  put 'set_rate_five', to: 'cocktails#set_rate_five'
  get 'cocktail_favorites', to: 'cocktails#favorites'

  resources :categories do
    resources :cocktails do
      get 'add_ingredient_form', to: 'cocktails#add_ingredient_form'
      post 'add_ingredient', to: 'cocktails#add_ingredient'
      resources :ingredients
    end
  end
end

cocktail-bar/app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :cocktails, dependent: :destroy

  validates :name, presence: true
end

cocktail-bar/app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show destroy]

  def index
    @hide = true
    @categories = Category.all
  end

  def show
    @cocktails = @category.cocktails
  end

  def new
    # @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path, notice: 'Category created successfully.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to categories_path, notice: 'Category updated successfully.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy

    render categories_path, notice: 'Category deleted successfully.'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

cocktail-bar/app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

cocktail-bar/app/views/categories/_category.html.erb
<!--<div class="category btn btn--dark">-->
  <%= link_to category.name.gsub(' / ', '/'), category_path(category), class: "category btn btn--dark", data: { turbo_frame: "cocktails" } %>
<!--</div>-->

cocktail-bar/app/views/categories/_search_bar.html.erb
<%= turbo_frame_tag "search_bar" do %>

<% end %>

cocktail-bar/app/views/categories/index.html.erb
<div id="options" data-controller="visibility">
  <div class="left_bar">
    <h1>Categories</h1>

    <%= link_to "Add cocktail", cocktail_form_path, class: "add_cocktail_btn", data: { turbo_frame: 'cocktails' } %>
    <%= link_to "Show favorites", cocktail_favorites_path, class: "add_cocktail_btn", data: { turbo_frame: 'cocktails' } %>
    <!--    <a data-action="visibility#toggleForm" class="add_cocktail_btn">Add cocktail</a>-->
    <div>
      <%= render @categories %>
    </div>
  </div>

  <div class="main">
    <div class="search_btn" id="search_btn_id" data-visibility-target="button">

      <a data-action="visibility#toggleTargets visibility#changeColorTargets"><%= image_tag('search.png') %></a>

    </div>

    <div class="search_bar" id="search_bar_id" data-visibility-target="hideable" hidden>
      <%= form_tag(search_path, method: :get, class: "search_form_tag", data: { turbo_frame: 'cocktails' }) do %>
        <%= text_field_tag(:search, params[:search], class: "search_text_field", placeholder: "Search for a cocktail...", data: { turbo_frame: 'cocktails' }) %>
      <% end %>
    </div>
  </div>

  <div class="cocktail_list">
    <%= turbo_frame_tag "cocktails" %>
  </div>
</div>

cocktail-bar/app/views/categories/show.html.erb
<%= link_to sanitize("&larr; Back to Categories"), categories_path %>

<%= turbo_frame_tag "cocktails" do %>
  <%#= render "cocktails/empty_state" %>
  <h1><%= @category.name %></h1>    <%= button_to image_tag('delete.png', width: 30, height: 30), category_path(id: @category), method: :delete, class: 'delete_btn' %>
  <br>
  <%= render @cocktails %>
<% end %>