cocktail-bar/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'categories#index'

  get 'search', to: 'cocktails#search'
  post 'create', to: 'cocktails#create'
  get 'cocktail_form', to: 'cocktails#cocktail_form'
  put 'set_like', to: 'cocktails#set_like'
  put 'set_like_show', to: 'cocktails#set_like_show'
  put 'set_rate_one', to: 'cocktails#set_rate_one'
  put 'set_rate_two', to: 'cocktails#set_rate_two'
  put 'set_rate_three', to: 'cocktails#set_rate_three'
  put 'set_rate_four', to: 'cocktails#set_rate_four'
  put 'set_rate_five', to: 'cocktails#set_rate_five'
  get 'cocktail_favorites', to: 'cocktails#favorites'

  resources :categories do
    resources :cocktails do
      get 'add_ingredient_form', to: 'cocktails#add_ingredient_form'
      post 'add_ingredient', to: 'cocktails#add_ingredient'
      resources :ingredients
    end
  end
end

cocktail-bar/app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  has_and_belongs_to_many :cocktails

  validates :name, presence: true
  validates :description, presence: true
  validates :picture, presence: true
end

cocktail-bar/app/controllers/ingredients_controller.rb
# frozen_string_literal: true

class IngredientsController < ApplicationController
  before_action :set_ingredient, only: :show
  before_action :set_cocktail, only: :show

  def show; end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end
end

cocktail-bar/app/helpers/ingredients_helper.rb
# frozen_string_literal: true

module IngredientsHelper
  def image_valid?(url)
    uri = URI(url)
    response = Net::HTTP.get_response(uri)
    response.code == '200'
  end
end

cocktail-bar/app/views/ingredients/_ingredient.html.erb
<%= link_to ingredient.name.titleize, category_cocktail_ingredient_path(id: ingredient, cocktail_id: @cocktail),  class: "btn" %><br>

cocktail-bar/app/views/ingredients/show.html.erb
<%= turbo_frame_tag "cocktails" do %>
  <%= link_to sanitize("&larr; Back to #{@cocktail.name}"), category_cocktail_path(id: @cocktail, category_id: @cocktail.category_id) %>
  <div class="cocktail_main">
    <h1><%= @ingredient.name.capitalize %></h1>

    <%
      img_url = "https://" + @ingredient.picture
      img_url = "no_image.png" unless image_valid?(img_url)
    %>
    <%= image_tag(img_url, alt: @ingredient.name, height: 300, width: 300) %>
    <%= @ingredient.description.capitalize %>
  </div>
<% end %>